config/routes.rb
UserManagement::Application.routes.draw do
  devise_for :users

  root :to => 'users#index' # change to sign in page later
  resources :users do 
    post 'table_update' => 'users#update' #using the update action for modifying the table content
  end
  resources :sessions, :only => [:new, :create, :destroy]  
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/role.rb
class Role < ActiveRecord::Base
  # == Schema Information
  #
  # Table name: roles
  #
  #  id         :integer         not null, primary key
  #  created_at :datetime
  #  updated_at :datetime
  #  title      :string(255)
  #
  has_and_belongs_to_many :users

  validates :title, :presence => true
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # == Schema Information
  #
  # Table name: users
  #
  #  id         :integer         not null, primary key
  #  username   :string(255)
  #  email      :string(255)
  #  fname      :string(255)
  #  lname      :string(255)
  #  created_at :datetime
  #  updated_at :datetime
  #  password   :string(255)
  #
  has_and_belongs_to_many :roles
  attr_accessor :password
  attr_accessible :username, 
                  :email, 
                  :fname, 
                  :lname, 
                  :password, 
                  :password_confirmation
  
  valid_email_format = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :username, :presence => true,
                       :uniqueness => {:case_sensitive => false},
                       :length => { :within => 4..16}

  validates :password, :presence => true,
                       :confirmation => true,
                       :length => {:within => 4..50},
                       :on => :create #solved the "password too short" error while updating
                       
  validates :email, :presence => true,
                    :uniqueness => { :case_sensitive => false},
                    :format => { :with => valid_email_format}
                    
  validates :fname, :presence => true,
                    :length => { :within => 2..30}
  
  validates :lname, :presence => true,
                    :length => { :within => 2..30}


  before_save :encrypt_password
  
  def has_password?(submitted_password) 
    # Comparing encrypted_password with the encrypted version of submitted_password.
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password) 
    user = find_by_email(email)
    return nil if user.nil? 
    return user if user.has_password?(submitted_password)
  end
  
  private
  
  def encrypt_password 
    self.salt = pw_salt if new_record?
    self.encrypted_password = encrypt(self.password)
  end
  
  def encrypt(string) 
    secure_hash("#{salt}--#{string}")
  end
  
  def pw_salt 
    secure_hash("#{Time.now.utc}--#{password}")
  end
  
  def secure_hash(string) 
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # include SessionsHelper
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserManagement</title>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "ui.jqgrid" %>
  <%= javascript_include_tag "application" %>
  <!-- <%= javascript_include_tag "grid.locale-en" %>
  <%= javascript_include_tag "jquery.jqGrid.min" %> jqgrid requires a url to obtain the data from the application which I can locate that for this application-->
  <%= csrf_meta_tags %>
</head>
<body>
	
<%= yield %>
<%= debug(params) if Rails.env.development?  %>

</body>
</html>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>UserSessions#new</h1>
<p>Find me in app/views/user_sessions/new.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div>
	<%= f.label :password_confirmation, "Retype password" %><br />
	<%= f.password_field :passsword_confirmation %>
  </div>
  <div class="field">
    <%= f.label :fname, "First Name" %><br />
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname, "Last Name" %><br />
    <%= f.text_field :lname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table id="userTable">
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Roles</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.fname %></td>
    <td><%= user.lname %></td>
    <td><%= user.roles.collect { |role| role.title }.join(', ') %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>


<p>Admin User? <%= link_to 'Sign In Here!', signin_path%></p>

<!-- <%= link_to 'Back', users_path %>--> 

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>First name:</b>
  <%= @user.fname %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.lname %>
</p>
<p>
	<b>Roles:</b> 
	<%= @user.roles.collect { |role| role.title }.join(', ') %>
</p>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>